name: Scheduled Test

on:
  schedule:
    - cron: '42 12 * * *'

jobs:
  test:
    name: Test with Latest Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: cargo hack --feature-powerset test --lib
        env:
          RUSTFLAGS: -D deprecated
